@startuml iluminacion

class Foco 
{
    - EstadoFoco estado
    + Encender()
    + Apagar()
    + EstadoFoco LeerEstado()
    
}
class EstadoFoco
class Persona

Foco *-- EstadoFoco
Persona *-- Foco
EstadoFoco --|> bool


@enduml